// What the frame and kit pages say when a scene or a brand fails (shown in the editor's preview, read by Claude), the
// kit sheet's section titles, and the sample content of the kit sheet in the editor's brand panel. The frame server writes
// the interface language in <html lang>; a language change reloads the editor and its frames.
const TEXTS = {
  fr: {
    runtimeError: (scene: string) => `Erreur d’exécution · ${scene}`,
    compileError: (scene: string) => `Erreur de compilation · ${scene}`,
    sceneNotFound: 'Scène introuvable',
    sceneMissing: (id: string) => `La scène « ${id} » n’existe pas dans ce projet.`,
    sceneExport: (id: string) => `scenes/${id}.tsx doit exporter par défaut un composant React`,
    soundsError: (scene: string) => `Erreur dans sounds() · ${scene}`,
    soundsExport: (id: string) => `L’export sounds de scenes/${id}.tsx doit être une fonction (props) => SoundCue[]`,
    soundCues: {
      notArray: 'sounds() doit renvoyer un tableau de sons',
      tooMany: (max: number) => `sounds() renvoie plus de ${max} sons`,
      notObject: (index: number) => `son ${index} : un objet { at, sound, gain? } est attendu`,
      at: (index: number, duration: number) => `son ${index} : at doit être un nombre de secondes entre 0 et ${duration}`,
      sound: (index: number, received: string, known: string) => `son ${index} : son inconnu ${received} (${known})`,
      gain: (index: number) => `son ${index} : gain doit être un nombre entre 0 et 1`,
    },
    kitExport: 'index.tsx doit exporter par défaut le BrandKit de la marque',
    brandFailed: (id: string, error: string) => `Impossible de charger la marque « ${id} » : ${error}`,
    projectFailed: (id: string, error: string) => `Impossible de charger le projet « ${id} » : ${error}`,
    fontFailed: (face: string) => `La police préchargée « ${face} » ne se charge pas`,
    sampleFailed: (name: string, error: string) => `${name} : ${error}`,
    sections: { colors: 'Couleurs', fonts: 'Polices', components: 'Composants', extras: 'Extras' },
    sheet: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      profile: 'Profil',
      name: 'Nom',
      saved: 'Enregistré il y a 2 minutes',
      active: 'Actif',
      month: 'Ce mois-ci',
      amount: '12 480 €',
      delta: '+12,4 %',
      tabs: ['Jour', 'Semaine', 'Mois'],
      notifications: 'Notifications',
      new: 'Nouveau',
      pending: 'En attente',
    },
  },
  en: {
    runtimeError: (scene: string) => `Runtime error · ${scene}`,
    compileError: (scene: string) => `Compile error · ${scene}`,
    sceneNotFound: 'Scene not found',
    sceneMissing: (id: string) => `The scene "${id}" does not exist in this project.`,
    sceneExport: (id: string) => `scenes/${id}.tsx must export a React component as its default`,
    soundsError: (scene: string) => `sounds() error · ${scene}`,
    soundsExport: (id: string) => `The sounds export of scenes/${id}.tsx must be a function (props) => SoundCue[]`,
    soundCues: {
      notArray: 'sounds() must return an array of cues',
      tooMany: (max: number) => `sounds() returns more than ${max} cues`,
      notObject: (index: number) => `sound cue ${index}: expected an object { at, sound, gain? }`,
      at: (index: number, duration: number) => `sound cue ${index}: at must be a number of seconds from 0 to ${duration}`,
      sound: (index: number, received: string, known: string) => `sound cue ${index}: unknown sound ${received} (${known})`,
      gain: (index: number) => `sound cue ${index}: gain must be a number from 0 to 1`,
    },
    kitExport: "index.tsx must export the brand's BrandKit as its default",
    brandFailed: (id: string, error: string) => `Could not load the brand "${id}": ${error}`,
    projectFailed: (id: string, error: string) => `Could not load the project "${id}": ${error}`,
    fontFailed: (face: string) => `The preloaded font "${face}" does not load`,
    sampleFailed: (name: string, error: string) => `${name}: ${error}`,
    sections: { colors: 'Colors', fonts: 'Fonts', components: 'Components', extras: 'Extras' },
    sheet: {
      save: 'Save',
      cancel: 'Cancel',
      profile: 'Profile',
      name: 'Name',
      saved: 'Saved 2 minutes ago',
      active: 'Active',
      month: 'This month',
      amount: '$12,480',
      delta: '+12.4%',
      tabs: ['Day', 'Week', 'Month'],
      notifications: 'Notifications',
      new: 'New',
      pending: 'Pending',
    },
  },
};

export const language = document.documentElement.lang === 'en' ? 'en' : 'fr';
export const texts = TEXTS[language];
